In [4]:
# Cell 1: Import necessary libraries
import pyreadstat
import pandas as pd

In [5]:
import os
os.getcwd()

'/Users/ushagartoula/NHANES_DATA'

In [6]:
import os
# Change to your data folder
os.chdir("/Users/ushagartoula/NHANES_DATA")

# Confirm
print(os.getcwd())

/Users/ushagartoula/NHANES_DATA

In [7]:
# Cell 2: Load dietary fiber data
diet, meta_diet = pyreadstat.read_xport("data/DR1TOT_L.xpt", encoding='latin1')
diet_subset = diet[['SEQN', 'DR1TFIBE']]  # SEQN = participant ID, DR1TFIBE = total fiber intake

# Inspect
print(diet_subset.head())
print(diet_subset.isnull().sum())

       SEQN  DR1TFIBE
0  130378.0      10.1
1  130379.0      29.6
2  130380.0      21.1
3  130381.0      11.5
4  130382.0      13.8
SEQN           0
DR1TFIBE    2166
dtype: int64

In [8]:
# Cell 3: Load fasting glucose data
glucose, meta_glu = pyreadstat.read_xport("data/GLU_L.xpt", encoding='latin1')
glucose_subset = glucose[['SEQN', 'LBXGLU']]  # SEQN = participant ID, LBXGLU = glucose

print(glucose_subset.head())
print(glucose_subset.isnull().sum())

       SEQN  LBXGLU
0  130378.0   113.0
1  130379.0    99.0
2  130380.0   156.0
3  130386.0   100.0
4  130394.0    88.0
SEQN        0
LBXGLU    324
dtype: int64

In [9]:
# Cell 4: Load demographics
demo, meta_demo = pyreadstat.read_xport("data/DEMO_L.xpt", encoding='latin1')
demo_subset = demo[['SEQN', 'RIAGENDR', 'RIDAGEYR']]  # Gender and age

print(demo_subset.head())
print(demo_subset.isnull().sum())

       SEQN  RIAGENDR  RIDAGEYR
0  130378.0       1.0      43.0
1  130379.0       1.0      66.0
2  130380.0       2.0      44.0
3  130381.0       2.0       5.0
4  130382.0       1.0       2.0
SEQN        0
RIAGENDR    0
RIDAGEYR    0
dtype: int64

In [10]:
# Cell 5: Load HDL cholesterol
hdl, meta_hdl = pyreadstat.read_xport("data/HDL_L.xpt", encoding='latin1')
hdl_subset = hdl[['SEQN', 'LBDHDD']]  # HDL in mg/dL

print(hdl_subset.head())
print(hdl_subset.isnull().sum())

       SEQN  LBDHDD
0  130378.0    45.0
1  130379.0    60.0
2  130380.0    49.0
3  130386.0    46.0
4  130387.0    42.0
SEQN         0
LBDHDD    1178
dtype: int64

In [11]:
# Cell 6: Load Total Cholesterol data
chol, meta_chol = pyreadstat.read_xport("data/TCHOL_L.xpt", encoding='latin1')

# Subset columns: SEQN = participant ID, LBXTC = total cholesterol
chol_subset = chol[['SEQN', 'LBXTC']]

# Inspect first 5 rows and missing values
print(chol_subset.head())
print(chol_subset.isnull().sum())

       SEQN  LBXTC
0  130378.0  264.0
1  130379.0  214.0
2  130380.0  187.0
3  130386.0  183.0
4  130387.0  203.0
SEQN        0
LBXTC    1178
dtype: int64

In [12]:
# Check all columns in the Triglycerides dataset
trig, meta_trig = pyreadstat.read_xport("data/TRIGLY_L.xpt", encoding='latin1')
print(trig.columns)

Index(['SEQN', 'WTSAF2YR', 'LBXTLG', 'LBDTRSI', 'LBDLDL', 'LBDLDLSI',
       'LBDLDLM', 'LBDLDMSI', 'LBDLDLN', 'LBDLDNSI'],
      dtype='object')

In [13]:
# Load Triglycerides subset using the correct column name
trig_subset = trig[['SEQN', 'LBXTLG']]

# Inspect
print(trig_subset.head())
print(trig_subset.isnull().sum())

       SEQN  LBXTLG
0  130378.0   153.0
1  130379.0    86.0
2  130380.0   375.0
3  130386.0   142.0
4  130394.0    57.0
SEQN        0
LBXTLG    479
dtype: int64

In [14]:
# Start with demographics
master_df = demo_subset.copy()

# Merge dietary fiber
master_df = master_df.merge(diet_subset, on='SEQN', how='inner')

# Merge glucose
master_df = master_df.merge(glucose_subset, on='SEQN', how='inner')

# Merge HDL
master_df = master_df.merge(hdl_subset, on='SEQN', how='inner')

# Merge Total Cholesterol
master_df = master_df.merge(chol_subset, on='SEQN', how='inner')

# Merge Triglycerides
master_df = master_df.merge(trig_subset, on='SEQN', how='inner')

# Inspect
print(master_df.head())
print(master_df.info())
print(master_df.isnull().sum())

       SEQN  RIAGENDR  RIDAGEYR  DR1TFIBE  LBXGLU  LBDHDD  LBXTC  LBXTLG
0  130378.0       1.0      43.0      10.1   113.0    45.0  264.0   153.0
1  130379.0       1.0      66.0      29.6    99.0    60.0  214.0    86.0
2  130380.0       2.0      44.0      21.1   156.0    49.0  187.0   375.0
3  130386.0       1.0      34.0      25.1   100.0    46.0  183.0   142.0
4  130394.0       1.0      51.0      19.7    88.0    48.0  183.0    57.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3996 entries, 0 to 3995
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3996 non-null   float64
 1   RIAGENDR  3996 non-null   float64
 2   RIDAGEYR  3996 non-null   float64
 3   DR1TFIBE  3114 non-null   float64
 4   LBXGLU    3672 non-null   float64
 5   LBDHDD    3546 non-null   float64
 6   LBXTC     3546 non-null   float64
 7   LBXTLG    3517 non-null   float64
dtypes: float64(8)
memory usage: 249.9 KB
None
SEQN          0
RIAGENDR      0
RIDAGEYR      0
DR1TFIBE    882
LBXGLU      324
LBDHDD      450
LBXTC       450
LBXTLG      479
dtype: int64

In [15]:
master_df.rename(columns={
    'SEQN': 'ID',
    'RIAGENDR': 'Gender',
    'RIDAGEYR': 'Age',
    'DR1TFIBE': 'Fiber',
    'LBXGLU': 'Glucose',
    'LBDHDD': 'HDL',
    'LBXTC': 'TotalChol',
    'LBXTLG': 'Triglycerides'
}, inplace=True)

# Inspect
print(master_df.head())

         ID  Gender   Age  Fiber  Glucose   HDL  TotalChol  Triglycerides
0  130378.0     1.0  43.0   10.1    113.0  45.0      264.0          153.0
1  130379.0     1.0  66.0   29.6     99.0  60.0      214.0           86.0
2  130380.0     2.0  44.0   21.1    156.0  49.0      187.0          375.0
3  130386.0     1.0  34.0   25.1    100.0  46.0      183.0          142.0
4  130394.0     1.0  51.0   19.7     88.0  48.0      183.0           57.0

In [16]:
# Display top 50 rows
master_df.head(50)

          ID  Gender   Age  Fiber  Glucose   HDL  TotalChol  Triglycerides
0   130378.0     1.0  43.0   10.1    113.0  45.0      264.0          153.0
1   130379.0     1.0  66.0   29.6     99.0  60.0      214.0           86.0
2   130380.0     2.0  44.0   21.1    156.0  49.0      187.0          375.0
3   130386.0     1.0  34.0   25.1    100.0  46.0      183.0          142.0
4   130394.0     1.0  51.0   19.7     88.0  48.0      183.0           57.0
5   130395.0     2.0  33.0    NaN    100.0   NaN        NaN            NaN
6   130396.0     2.0  56.0    NaN    104.0  68.0      214.0          108.0
7   130397.0     2.0  67.0    9.4    138.0   NaN        NaN            NaN
8   130398.0     1.0  47.0   24.7    107.0  41.0      189.0          146.0
9   130402.0     2.0  26.0    NaN     73.0  54.0      135.0           84.0
10  130404.0     2.0  73.0   11.8    100.0  53.0      179.0          150.0
11  130408.0     1.0  80.0    NaN     89.0  82.0      169.0           45.0
12  130413.0     2.0  67.0   13.2     95.0  56.0      217.0           91.0
13  130416.0     2.0  59.0    NaN     91.0  47.0      189.0           81.0
14  130418.0     1.0  53.0    3.9     96.0  41.0      155.0           86.0
15  130420.0     1.0  18.0    3.3     98.0  32.0      219.0          379.0
16  130422.0     1.0  66.0   18.4     98.0  43.0      165.0          157.0
17  130424.0     2.0  19.0    NaN     87.0  47.0      165.0           69.0
18  130429.0     1.0  14.0    NaN    101.0  64.0      214.0           89.0
19  130433.0     2.0  14.0   10.0    102.0  60.0      169.0           83.0
20  130435.0     1.0  17.0    NaN    115.0  46.0      116.0           77.0
21  130436.0     1.0  50.0    NaN    104.0  49.0      129.0           69.0
22  130437.0     2.0  43.0   24.5     99.0  37.0      194.0          284.0
23  130441.0     2.0  33.0   19.2    100.0  64.0      192.0           57.0
24  130442.0     1.0  43.0   11.9    117.0  53.0      165.0          153.0
25  130443.0     1.0  41.0    NaN     83.0  40.0      151.0           57.0
26  130444.0     2.0  77.0   35.3     94.0  58.0      188.0           98.0
27  130457.0     2.0  38.0   27.3     95.0  66.0      168.0           86.0
28  130460.0     1.0  15.0   20.2     97.0  54.0      154.0           60.0
29  130465.0     1.0  77.0   11.7    126.0  40.0       84.0           58.0
30  130473.0     2.0  26.0   13.7     92.0  60.0      216.0           90.0
31  130475.0     2.0  55.0   13.1    167.0  38.0      155.0          131.0
32  130478.0     2.0  69.0   13.3     84.0  75.0      197.0           70.0
33  130480.0     2.0  16.0    NaN     92.0  47.0      120.0           57.0
34  130484.0     2.0  22.0   15.2      NaN   NaN        NaN            NaN
35  130489.0     1.0  57.0    4.3    163.0  53.0      172.0           90.0
36  130492.0     2.0  18.0   11.4     90.0  44.0      133.0           60.0
37  130494.0     2.0  73.0    NaN     98.0  54.0      217.0           69.0
38  130495.0     1.0  60.0    8.3    106.0  53.0      164.0           78.0
39  130502.0     1.0  71.0   15.2    108.0  84.0      196.0           61.0
40  130504.0     2.0  67.0   14.1    149.0  48.0      167.0           65.0
41  130517.0     1.0  30.0    NaN     98.0  44.0      193.0           82.0
42  130520.0     1.0  29.0   14.4     93.0  52.0      145.0           59.0
43  130522.0     1.0  58.0    6.0     99.0  40.0      144.0          254.0
44  130523.0     2.0  61.0   40.3     78.0  63.0      237.0          187.0
45  130525.0     1.0  70.0   23.1    120.0  72.0      189.0           60.0
46  130527.0     1.0  79.0   22.6    163.0  64.0      161.0           87.0
47  130528.0     2.0  17.0    2.3      NaN   NaN        NaN            NaN
48  130530.0     2.0  69.0   16.9    105.0  78.0      239.0           91.0
49  130533.0     1.0  80.0   16.0    149.0  33.0      103.0          337.0

In [18]:
master_df.describe()

,ID,Gender,Age,Fiber,Glucose,HDL,TotalChol,Triglycerides
count,3996.000000,3996.000000,3996.000000,3114.000000,3672.000000,3546.000000,3546.000000,3517.000000
mean,136384.084084,1.549550,48.638639,16.254399,107.884532,54.509306,183.126904,115.967302
std,3452.307779,0.497601,20.891412,10.431201,32.476268,14.322738,43.005589,84.368104
min,130378.000000,1.000000,12.000000,0.000000,59.000000,23.000000,62.000000,19.000000
25%,133373.750000,1.000000,31.000000,9.200000,93.000000,44.000000,152.000000,70.000000
50%,136412.500000,2.000000,52.000000,14.200000,100.000000,53.000000,180.000000,96.000000
75%,139339.750000,2.000000,66.000000,20.700000,109.000000,62.000000,210.000000,136.000000
max,142309.000000,2.000000,80.000000,117.300000,561.000000,159.000000,405.000000,1745.000000

In [24]:
# Check extreme values in each variable
print("Fiber > 60g:          ", (master_df['Fiber'] > 60).sum())
print("Glucose > 400:        ", (master_df['Glucose'] > 400).sum())
print("Triglycerides > 1000: ", (master_df['Triglycerides'] > 1000).sum())
print("TotalChol < 100:      ", (master_df['TotalChol'] < 100).sum())
print("Age under 20:         ", (master_df['Age'] < 20).sum())

Fiber > 60g:           21
Glucose > 400:         3
Triglycerides > 1000:  3
TotalChol < 100:       34
Age under 20:          571

In [25]:
# Inspect the low cholesterol participants before deciding
low_chol = master_df[master_df['TotalChol'] < 100]
print(low_chol[['ID', 'Age', 'Gender', 'TotalChol', 'Glucose', 'Triglycerides']].to_string())

            ID   Age  Gender  TotalChol  Glucose  Triglycerides
29    130465.0  77.0     1.0       84.0    126.0           58.0
142   130801.0  56.0     1.0       88.0    103.0           78.0
179   130898.0  13.0     1.0       93.0     80.0           31.0
410   131633.0  13.0     1.0       94.0    102.0           28.0
547   132073.0  79.0     1.0       95.0    108.0           44.0
590   132195.0  14.0     1.0       88.0     90.0           35.0
902   133101.0  45.0     1.0       89.0    122.0          106.0
1030  133484.0  74.0     1.0       86.0    209.0           99.0
1050  133536.0  68.0     1.0       84.0    131.0          114.0
1147  133827.0  67.0     1.0       88.0    110.0           60.0
1295  134280.0  25.0     2.0       87.0     83.0           29.0
1313  134346.0  13.0     1.0       95.0     91.0           37.0
1672  135458.0  30.0     1.0       91.0     96.0            NaN
1686  135499.0  70.0     1.0       94.0    119.0          127.0
1952  136285.0  72.0     1.0       94.0    135.0           81.0
2067  136607.0  59.0     1.0       62.0    152.0           57.0
2243  137107.0  40.0     1.0       99.0     99.0           85.0
2251  137126.0  68.0     1.0       97.0    108.0           68.0
2557  138036.0  50.0     2.0       97.0    115.0           61.0
2647  138286.0  19.0     2.0       90.0     92.0           53.0
2661  138340.0  12.0     1.0       88.0     93.0           98.0
2710  138501.0  28.0     2.0       89.0    107.0           80.0
2881  139011.0  26.0     2.0       63.0     77.0           19.0
2900  139085.0  62.0     1.0       91.0    124.0           90.0
3010  139376.0  41.0     2.0       98.0     88.0           34.0
3125  139738.0  31.0     1.0       97.0    125.0           97.0
3353  140506.0  80.0     1.0       81.0     76.0           70.0
3434  140714.0  63.0     1.0       84.0    145.0           72.0
3450  140777.0  53.0     2.0       86.0    118.0           98.0
3654  141324.0  26.0     2.0       97.0     98.0           45.0
3666  141361.0  17.0     1.0       99.0    105.0           84.0
3894  142021.0  80.0     1.0       93.0    113.0           97.0
3897  142036.0  67.0     2.0       95.0    114.0          239.0
3924  142103.0  66.0     2.0       80.0     81.0           38.0

In [26]:
import pandas as pd
import numpy as np

# ── STEP 1: CHECK YOUR STARTING POINT ────────────────────────────────────────
# Before removing anything, record how many participants we started with
original_size = len(master_df)
print(f"Original sample size: {original_size}")


# ── STEP 2: REMOVE PARTICIPANTS UNDER 20 ─────────────────────────────────────
# NHANES metabolic research is standardly restricted to adults 20 and older
# Adolescent glucose and lipid reference ranges are physiologically different
# Mixing them with adults would make findings harder to interpret


# ── STEP 3: REMOVE IMPLAUSIBLE FIBER VALUES (> 60g) ──────────────────────────
# Recommended daily fiber intake is 25-38g
# Values above 60g from a single 24-hour recall are likely reporting errors
# We use isnull() condition to KEEP rows where fiber is missing
# We are not removing people for missing data — only for implausible values


# ── STEP 4: REMOVE EXTREME GLUCOSE VALUES (> 400 mg/dL) ──────────────────────
# Only 3 participants had glucose above 400
# These are real but extreme values that would disproportionately
# distort our regression analysis of fiber vs glucose


# ── STEP 5: REMOVE EXTREME TRIGLYCERIDE VALUES (> 1000 mg/dL) ────────────────
# Only 3 participants had triglycerides above 1000
# Severe hypertriglyceridemia is real but these extreme values
# would dominate and skew the entire analysis


# ── STEP 6: REMOVE IMPLAUSIBLE TOTAL CHOLESTEROL VALUES (< 70 mg/dL) ─────────
# After inspecting the 34 low cholesterol participants:
# - Values of 62 and 63 mg/dL are almost certainly data errors
# - Values between 70-99 mg/dL are unusual but clinically defensible
# - We set the cutoff at 70 mg/dL to remove only clear errors


# ── APPLY ALL FILTERS TOGETHER ────────────────────────────────────────────────
master_df_clean = master_df[
    (master_df['Age'] >= 20) &                                              # Adults only
    ((master_df['Fiber'] <= 60) | (master_df['Fiber'].isnull())) &         # Remove implausible fiber
    ((master_df['Glucose'] <= 400) | (master_df['Glucose'].isnull())) &    # Remove extreme glucose
    ((master_df['Triglycerides'] <= 1000) | (master_df['Triglycerides'].isnull())) &  # Remove extreme TG
    ((master_df['TotalChol'] >= 70) | (master_df['TotalChol'].isnull()))   # Remove implausible cholesterol
].copy()


# ── STEP 7: RESET INDEX ───────────────────────────────────────────────────────
# After filtering, row numbers will have gaps (e.g. 0, 2, 5...)
# Resetting gives us clean sequential index (0, 1, 2, 3...)
master_df_clean = master_df_clean.reset_index(drop=True)


# ── STEP 8: VERIFY YOUR RESULTS ───────────────────────────────────────────────
print(f"Original sample:        {original_size}")
print(f"Clean sample:           {len(master_df_clean)}")
print(f"Participants removed:   {original_size - len(master_df_clean)}")

print(f"\nMissing values in clean dataset:")
print(master_df_clean.isnull().sum())

Original sample size: 3996
Original sample:        3996
Clean sample:           3399
Participants removed:   597

Missing values in clean dataset:
ID                 0
Gender             0
Age                0
Fiber            698
Glucose          215
HDL              324
TotalChol        324
Triglycerides    346
dtype: int64

In [27]:
# ── CREATE MISSING INDICATOR FLAGS ───────────────────────────────────────────
# For each variable with missing data, we create a new column
# 1 = data is MISSING for that participant
# 0 = data is PRESENT for that participant
# This lets us statistically compare the two groups

master_df_clean['Fiber_missing']   = master_df_clean['Fiber'].isnull().astype(int)
master_df_clean['Glucose_missing'] = master_df_clean['Glucose'].isnull().astype(int)
master_df_clean['HDL_missing']     = master_df_clean['HDL'].isnull().astype(int)


# ── CHECK IF MISSINGNESS IS RELATED TO AGE ───────────────────────────────────
# If people of certain ages are more likely to have missing data,
# missingness is NOT random — it is related to an observed variable (MAR)

print("=== Average Age: Fiber Missing vs Present ===")
print(master_df_clean.groupby('Fiber_missing')['Age'].mean())

print("\n=== Average Age: Glucose Missing vs Present ===")
print(master_df_clean.groupby('Glucose_missing')['Age'].mean())

print("\n=== Average Age: HDL Missing vs Present ===")
print(master_df_clean.groupby('HDL_missing')['Age'].mean())


# ── CHECK IF MISSINGNESS IS RELATED TO GENDER ────────────────────────────────
# Gender = 1 is Male, Gender = 2 is Female in NHANES
# If one gender has more missing data, missingness is related to gender (MAR)

print("\n=== Gender Distribution: Fiber Missing vs Present ===")
print(master_df_clean.groupby('Fiber_missing')['Gender'].value_counts())

print("\n=== Gender Distribution: Glucose Missing vs Present ===")
print(master_df_clean.groupby('Glucose_missing')['Gender'].value_counts())


# ── CHECK HOW MANY VARIABLES EACH PARTICIPANT IS MISSING ─────────────────────
# If the same people are missing fiber AND glucose AND lipids,
# that is a pattern — those participants likely skipped entire
# portions of the NHANES protocol, which is meaningful and not random

master_df_clean['total_missing'] = master_df_clean[
    ['Fiber', 'Glucose', 'HDL', 'TotalChol', 'Triglycerides']
].isnull().sum(axis=1)

print("\n=== How Many Variables Missing Per Participant ===")
print(master_df_clean['total_missing'].value_counts().sort_index())

=== Average Age: Fiber Missing vs Present ===
Fiber_missing
0    55.482044
1    49.293696
Name: Age, dtype: float64

=== Average Age: Glucose Missing vs Present ===
Glucose_missing
0    54.385364
1    51.632558
Name: Age, dtype: float64

=== Average Age: HDL Missing vs Present ===
HDL_missing
0    54.335285
1    53.033951
Name: Age, dtype: float64

=== Gender Distribution: Fiber Missing vs Present ===
Fiber_missing  Gender
0              2.0       1512
               1.0       1189
1              2.0        370
               1.0        328
Name: count, dtype: int64

=== Gender Distribution: Glucose Missing vs Present ===
Glucose_missing  Gender
0                2.0       1765
                 1.0       1419
1                2.0        117
                 1.0         98
Name: count, dtype: int64

=== How Many Variables Missing Per Participant ===
total_missing
0    2448
1     607
2      14
3     105
4     168
5      57
Name: count, dtype: int64